version: "3.9"
services:
  mysqldb:
    image: "mysql:8.0.29"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=urldb
      - MYSQL_ROOT_PASSWORD=password
  back:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/urldb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      - mysqldb
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
