version: "3.9"
services:
  db:
    image: "mysql:8.0.29"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: urldb 
      MYSQL_ROOT_PASSWORD: password
  back:
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
